package application;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class MainSceneController {
	
	@FXML
	private TextField usernameTextField;
	@FXML
	private TextField passwordTextField;

	// Event Listener on TextField.onAction
	@FXML
	public void usernameTextField(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void passwordTextField(ActionEvent event) {
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void btnOkClicked(ActionEvent event) {
		// TODO Autogenerated
		Stage mainWindow = (Stage) usernameTextField.getScene().getWindow();
		String username = usernameTextField.getText();
		String password = passwordTextField.getText();
		Main.receiveMail(username, password);
	}
}
