package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.time.LocalDate;

import javafx.event.ActionEvent;

public class MainSceneController {
	
	@FXML
	private TextField usernameTextField;
	@FXML
	private TextField passwordTextField;
	@FXML
	private DatePicker fromDatePicker;
	@FXML
	private DatePicker toDatePicker;
	
	DataSingleton data = DataSingleton.getInstance();

	// Event Listener on TextField.onAction
	@FXML
	public void usernameTextField(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void passwordTextField(ActionEvent event) {

	}
	
	// Event Listener on Button.onAction
	@FXML
	public void btnOkClicked(ActionEvent event) throws IOException {
		Stage mainWindow = (Stage) usernameTextField.getScene().getWindow();	
		String username = usernameTextField.getText();
		String password = passwordTextField.getText();
		
		data.setShifts(Main.receiveMail(username, password, fromDatePicker.getValue(), toDatePicker.getValue()));
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("DisplayDataScene.fxml"));
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		
		Parent root = loader.load();

	    Scene scene = new Scene(root);
	    stage.setScene(scene);
	    stage.show();
		
	}
}
